# coding: utf-8

"""
    OpenAlex

    ![](https://raw.githubusercontent.com/ourresearch/openalex-docs/main/.gitbook/assets/OpenAlex-logo-5.png)  **OpenAlex** is a fully open catalog of the global research system.  It's named after the [ancient Library of Alexandria](https://en.wikipedia.org/wiki/Library_of_Alexandria) and made by the nonprofit [OurResearch](https://ourresearch.org/).  This OpenAPI specification is derived from spec generated by [openapi-devtools](https://github.com/AndrewWalsh/openapi-devtools).

    The version of the OpenAPI document: 0.0.4-3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mearman_openalex_api.models.location import Location

class TestLocation(unittest.TestCase):
    """Location unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Location:
        """Test Location
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Location`
        """
        model = Location()
        if include_optional:
            return Location(
                is_accepted = None,
                is_oa = None,
                is_published = None,
                landing_page_url = None,
                license = None,
                pdf_url = None,
                source = mearman_openalex_api.models.location_source.location_source(
                    display_name = null, 
                    host_organization = null, 
                    host_organization_lineage = null, 
                    host_organization_lineage_names = null, 
                    host_organization_name = null, 
                    id = null, 
                    is_in_doaj = null, 
                    is_oa = null, 
                    issn = null, 
                    issn_l = null, 
                    type = null, ),
                version = None
            )
        else:
            return Location(
                is_accepted = None,
                is_oa = None,
                is_published = None,
                landing_page_url = None,
                source = mearman_openalex_api.models.location_source.location_source(
                    display_name = null, 
                    host_organization = null, 
                    host_organization_lineage = null, 
                    host_organization_lineage_names = null, 
                    host_organization_name = null, 
                    id = null, 
                    is_in_doaj = null, 
                    is_oa = null, 
                    issn = null, 
                    issn_l = null, 
                    type = null, ),
                version = None,
        )
        """

    def testLocation(self):
        """Test Location"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
