# coding: utf-8

"""
    OpenAlex

    ![](https://raw.githubusercontent.com/ourresearch/openalex-docs/main/.gitbook/assets/OpenAlex-logo-5.png)  **OpenAlex** is a fully open catalog of the global research system.  It's named after the [ancient Library of Alexandria](https://en.wikipedia.org/wiki/Library_of_Alexandria) and made by the nonprofit [OurResearch](https://ourresearch.org/).  This OpenAPI specification is derived from spec generated by [openapi-devtools](https://github.com/AndrewWalsh/openapi-devtools).

    The version of the OpenAPI document: 0.0.4-3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mearman_openalex_api.api.autocomplete_api import AutocompleteApi


class TestAutocompleteApi(unittest.TestCase):
    """AutocompleteApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AutocompleteApi()

    def tearDown(self) -> None:
        pass

    def test_get_autocomplete(self) -> None:
        """Test case for get_autocomplete

        /autocomplete
        """
        pass

    def test_get_autocomplete_authors(self) -> None:
        """Test case for get_autocomplete_authors

        /autocomplete/authors
        """
        pass

    def test_get_autocomplete_concepts(self) -> None:
        """Test case for get_autocomplete_concepts

        /autocomplete/concepts
        """
        pass

    def test_get_autocomplete_funders(self) -> None:
        """Test case for get_autocomplete_funders

        /autocomplete/funders
        """
        pass

    def test_get_autocomplete_institutions(self) -> None:
        """Test case for get_autocomplete_institutions

        /autocomplete/institutions
        """
        pass

    def test_get_autocomplete_publishers(self) -> None:
        """Test case for get_autocomplete_publishers

        /autocomplete/publishers
        """
        pass

    def test_get_autocomplete_sources(self) -> None:
        """Test case for get_autocomplete_sources

        /autocomplete/sources
        """
        pass

    def test_get_autocomplete_works(self) -> None:
        """Test case for get_autocomplete_works

        /autocomplete/works
        """
        pass


if __name__ == '__main__':
    unittest.main()
