# coding: utf-8

"""
    OpenAlex

    ![](https://raw.githubusercontent.com/ourresearch/openalex-docs/main/.gitbook/assets/OpenAlex-logo-5.png)  **OpenAlex** is a fully open catalog of the global research system.  It's named after the [ancient Library of Alexandria](https://en.wikipedia.org/wiki/Library_of_Alexandria) and made by the nonprofit [OurResearch](https://ourresearch.org/).  ## OpenAPI Specification  [Mearman/openalex-api-spec](https://github.com/Mearman/openalex-api-spec)  This OpenAPI specification is reverse-engineered and derived from spec generated by [openapi-devtools](https://github.com/AndrewWalsh/openapi-devtools).  The specification document itself is OpenAPI version 3.1 and is generated from TypeScript source code.  **[Releases](https://github.com/Mearman/openalex-api-spec/releases)**  ## Clients  ### Python  [![GitHub](https://img.shields.io/badge/GitHub-181717?style=for-the-badge&logo=GitHub&link=https://github.com/Mearman/openalex-python)](https://github.com/Mearman/openalex-python) [![CodeSpaces](https://img.shields.io/badge/CodeSpaces-181717?style=for-the-badge&logo=GitHub&link=https://codespaces.new/Mearman/openalex-python)](https://codespaces.new/Mearman/openalex-python) [![Colab](https://img.shields.io/badge/Colab-gray?style=for-the-badge&logo=Google%20Colab&link=https://colab.research.google.com/github/Mearman/openalex-python/blob/main/demos/notebook.ipynb)](https://colab.research.google.com/github/Mearman/openalex-python/blob/main/demos/notebook.ipynb)  ### Many more coming soon  ---

    The version of the OpenAPI document: 0.0.4-3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class LocationSource(BaseModel):
    """
    LocationSource
    """ # noqa: E501
    display_name: Optional[Any] = None
    host_organization: Optional[Any] = None
    host_organization_lineage: Optional[Any] = None
    host_organization_lineage_names: Optional[Any] = None
    host_organization_name: Optional[Any] = None
    id: Optional[Any] = None
    is_in_doaj: Optional[Any] = None
    is_oa: Optional[Any] = None
    issn: Optional[Any] = None
    issn_l: Optional[Any] = None
    type: Optional[Any] = None
    __properties: ClassVar[List[str]] = ["display_name", "host_organization", "host_organization_lineage", "host_organization_lineage_names", "host_organization_name", "id", "is_in_doaj", "is_oa", "issn", "issn_l", "type"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LocationSource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['display_name'] = None

        # set to None if host_organization (nullable) is None
        # and model_fields_set contains the field
        if self.host_organization is None and "host_organization" in self.model_fields_set:
            _dict['host_organization'] = None

        # set to None if host_organization_lineage (nullable) is None
        # and model_fields_set contains the field
        if self.host_organization_lineage is None and "host_organization_lineage" in self.model_fields_set:
            _dict['host_organization_lineage'] = None

        # set to None if host_organization_lineage_names (nullable) is None
        # and model_fields_set contains the field
        if self.host_organization_lineage_names is None and "host_organization_lineage_names" in self.model_fields_set:
            _dict['host_organization_lineage_names'] = None

        # set to None if host_organization_name (nullable) is None
        # and model_fields_set contains the field
        if self.host_organization_name is None and "host_organization_name" in self.model_fields_set:
            _dict['host_organization_name'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if is_in_doaj (nullable) is None
        # and model_fields_set contains the field
        if self.is_in_doaj is None and "is_in_doaj" in self.model_fields_set:
            _dict['is_in_doaj'] = None

        # set to None if is_oa (nullable) is None
        # and model_fields_set contains the field
        if self.is_oa is None and "is_oa" in self.model_fields_set:
            _dict['is_oa'] = None

        # set to None if issn (nullable) is None
        # and model_fields_set contains the field
        if self.issn is None and "issn" in self.model_fields_set:
            _dict['issn'] = None

        # set to None if issn_l (nullable) is None
        # and model_fields_set contains the field
        if self.issn_l is None and "issn_l" in self.model_fields_set:
            _dict['issn_l'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of LocationSource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "display_name": obj.get("display_name"),
            "host_organization": obj.get("host_organization"),
            "host_organization_lineage": obj.get("host_organization_lineage"),
            "host_organization_lineage_names": obj.get("host_organization_lineage_names"),
            "host_organization_name": obj.get("host_organization_name"),
            "id": obj.get("id"),
            "is_in_doaj": obj.get("is_in_doaj"),
            "is_oa": obj.get("is_oa"),
            "issn": obj.get("issn"),
            "issn_l": obj.get("issn_l"),
            "type": obj.get("type")
        })
        return _obj


